### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by rubyFeedback** [gosu/gosu-examples#15]
DEPRECATION WARNING: draw is deprecated; use Font#draw_text or Font#draw_markup instead.
draw called from /Depot/j/gosu-examples-1.0.5/lib/gosu-examples/sidebar.rb:26:in `draw'.

I think simply using draw_text rather than draw should suffice fine; I have been working
through old gosu examples and the old ones have lots of deprecation warnings by the
way. Unsurprising. :)

Perhaps gosu-examples could be changed into "gosu-addons" or something and 
integrate not only examples but modifications to gosu itself, including some physics stuff
and such like collision calculations and what not. Like to make it easier in general to
create games without having to think too much.

**Comment by jlnr** [comment]
Thanks for the reminder, I keep forgetting to fix this. :+1: Yes, it should be replaced by `draw_text`. Feel free to open a pull request, I probably won't get to it today.

I am staying away from offering official add-ons because there are too many ways to write collision detection and physics code, and part of the charm of 2D games is that each of them feels very different.

**Comment by jlnr** [comment]
Finally resolved in v1.0.7! Thanks again for nudging me.
